language: go

go:
    - tip

before_install:
    - go get github.com/axw/gocov/gocov
    - go get github.com/mattn/goveralls
    - go get golang.org/x/tools/cmd/cover

script:
    - $HOME/gopath/bin/goveralls -repotoken 4fVMZBABD867oTN7Xwvp0sarVSBY3VtDJ

notifications:
  email:
    recipients:
      - travis@simon.waldherr.eu
    on_success: always
    on_failure: always
