language: go

go:
  - 1.1
  - 1.2
  - 1.3
  - tip

script:
    - go get github.com/SimonWaldherr/ColorConverterGo && go test -v .

notifications:
  email:
    recipients:
      - travis@simon.waldherr.eu
    on_success: always
    on_failure: always
